### ISSUE TITLE
How to use homepage_url

### ISSUE THREAD

**Issue by hexylena** [galaxy-iuc/standards#1]
(Transcribed from previous thread https://github.com/galaxyproject/tools-iuc/pull/74)

| Case | `homepage_url` | notes |
| --- | --- | --- |
| package of upstream | upstream's home |  |
| simple wrapper tool for package of upstream | upstream's home | repository_url will be used to get to the XML development |
| complex wrapper (e.g. with `*.py`) for package of upstream | `repository_url == homepage_url` ? | Here package's URL could be mentioned in README (hopefully conflated with long_description), or there could be better viz of package_\* which mentions upstream.  e.g. @peterjc's `blast2go`/`b2g4pipe` wrapper |
| new tool, perhaps building on upstream tools | `repository_url == homepage_url` | @peterjc's `blast_rbh`, etc |

**Comment by hexylena** [comment]
@peterjc @nsoranzo @bgruening @jmchilton [docs are live](https://galaxy-iuc-standards.readthedocs.org/en/latest/). Anything else I should include?

**Comment by peterjc** [comment]
A better example of a complex wrapper (with `*.py` helper scripts) for an upstream package would for Blast2GO for pipelines, b2g4pipe: https://github.com/peterjc/galaxy_blast/tree/master/tools/blast2go

I don't regard `blast_rbh` as a complex wrapper for BLAST, but as a tool in its own right with a package dependency on the BLAST+ binaries: https://github.com/peterjc/galaxy_blast/tree/master/tools/blast_rbh

Likewise, https://github.com/peterjc/pico_galaxy/tree/master/tools/align_back_trans is a Python script with a package dependency on Biopython.

**Comment by hexylena** [comment]
@peterjc yes, great examples. Sorry, of course, blast_rbh is definitely a tool in its own right, I didn't mean imply that it wasn't, I was just lacking for examples and that was a convenient one (despite not knowing how much work went into it in the first place).

**Comment by peterjc** [comment]
No problem. I've edited it to move my `b2g4pipe` wrapper in the category of complex wrapper. All the extra code I wrote was just to facilitate running the tool within the Galaxy framework (including dealing with the tool's limitations with modern BLAST XML output - hopefully they fixed that in the replacement commercial tool), rather than any scientific novelty.

**Comment by bgruening** [comment]
Let's try to give this discussion a new spin.

Imho the intention of `repository_url` and `homepage_url` is to collect information in a structured way to advertise our tools/wrappers. This is purely to give more credits to tool developers. I don't think `repository_url` and `homepage_url` are useful yet. Mainly, because we are lacking a nice HTML5 Tool Shed UI that highlights the author and related websites.

Assumption: We want to have a nice Tool Shed UI with a lot of links, gravtar icons, orcid and so on...

To make this happen, we need a nice way to provide such informations to a repository. But which informations are repository dependent, which are author depended? Can we tackle this with a single readme file, or do we want to generate a Tool Shed website from provided metadata?

We should discuss this in one of our next hangouts. Moreover, we should discuss the Tool Shed UI in more detail with @martenson. I really think this entire discussion depends heavily on our vision of the new Tool Shed UI. If you haven't figured out what we want to see in the TS we can not define variables.

My vote for now is: `repository_url` to the repository where the `.shed.yml` file is stored and `homepage_url` is undefined for the moment. Until we really know more about the Tool Shed UI.

**Comment by hexylena** [comment]
+1 to that assumption, and to the 'cosmetic' issue of not displaying the information nicely highlighting who contributed where.

Agreed, definitely should discuss this over the next hangout.

If your vote is for `homepage_url` undefined, would you be able to close out galaxyproject/tools-iuc#74? The current PR there is with `repository_url` being the location of the `.shed.yml`.

**Comment by hexylena** [comment]
This issue is a month old. Does anyone have any continuing opinions on this or should we close it?

**Comment by bgruening** [comment]
I guess we can close this and wait for a UI outline from @martenson.

**Comment by martenson** [comment]
The typical usage of homepage_url crystalized fairly well I think.
